FROM ${NAMESPACE}/base:${TAG}
MAINTAINER ${MAINTAINER}

WORKDIR /tmp
RUN apt-get update
RUN wget https://apt.puppetlabs.com/puppetlabs-release-trusty.deb
RUN dpkg -i puppetlabs-release-trusty.deb
RUN apt-get update

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*