FROM ${NAMESPACE}/mcollective-common:${TAG}
MAINTAINER ${MAINTAINER}

COPY rc.local /etc/rc.local

# From Learning MCollective
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y mcollective-client mcollective-filemgr-client mcollective-nettest-client mcollective-package-client \
        mcollective-service-client mcollective-puppet-client && \
    chmod +x /etc/rc.local

COPY client.cfg /etc/mcollective/client.cfg