FROM ${NAMESPACE}/java:${TAG}
MAINTAINER ${MAINTAINER}

# From Learning MCollective
RUN apt-get update
RUN apt-get install -y ruby-stomp mcollective-plugins-facts-facter
RUN apt-get install -y mcollective
RUN update-rc.d mcollective defaults

ADD server.cfg /etc/mcollective/server.cfg.tpl

ADD rc.local /etc/rc.local
RUN chmod +x /etc/rc.local
RUN echo "RUN=yes" > /etc/default/mcollective
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*