FROM ${NAMESPACE}/java:${TAG}
MAINTAINER ${MAINTAINER}

# From Learning MCollective
RUN apt-get update
RUN apt-get install -y mcollective
RUN update-rc.d mcollective defaults

ADD server.cfg /etc/mcollective/server.cfg

ADD rc.local /etc/rc.local
RUN chmod +x /etc/rc.local
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*