#!/bin/bash

set -a
JAVA_HOME="/usr/lib/jvm/java"
source "/etc/default/tomcat"
CATALINA_HOME="/opt/tomcat"
CATALINA_BASE="/opt/tomcat"
JAVA_OPTS="-XX:MaxPermSize=128m -Djava.awt.headless=true -Xmx128M -XX:+HeapDumpOnOutOfMemoryError"
CATALINA_PID="/var/run/tomcat.pid"
CATALINA_TMPDIR="/tmp/tomcat-tmp"
LANG="en_US.UTF-8"
JSSE_HOME="/usr/lib/jvm/java/jre/"
cd "/opt/tomcat"

exec 2>&1
exec setuser -u tomcat /opt/tomcat/bin/catalina.sh run

# vim: syntax=sh ts=4 sw=4 sts=4 sr noet
