FROM ${NAMESPACE}/base:${TAG}
MAINTAINER ${MAINTAINER}

COPY rc.local /etc/rc.local

RUN \
  DEBIAN_FRONTEND=noninteractive \
  apt-get install -y apache2

# COPY proxy.conf /etc/apache2/conf/proxy.conf

VOLUME ["/var/www", "/etc/apache2"]

EXPOSE 80
# Run with
# cd [apache-module-workdir];
# docker run -d -p [port]:80 ${NAMESPACE}/apache
