FROM ${NAMESPACE}/base:${TAG}
MAINTAINER ${MAINTAINER}

COPY rc.local /etc/rc.local

RUN DEBIAN_FRONTEND=noninteractive apt-get -y install ruby python python3-pygments git ruby-dev make nodejs && \
    gem install jekyll && \
    groupadd jekyll && \
    mkdir /var/www && \
    /usr/sbin/useradd -m -d /var/www/jekyll -g jekyll -G jekyll -c "Jekyll user" jekyll && \
    chown -R jekyll:jekyll /var/www/jekyll && \
    chmod +x /etc/rc.local 

VOLUME /var/www/jekyll

EXPOSE 4000